version: '3.8'
services:
  patient-service:
    image: patient-service-image
    container_name: patient-service-container
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Mantendo a porta da aplicação
    depends_on:
      - patient-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/patient-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sfA547Dmo
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SERVER_PORT=4000

  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_DB: patient-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sfA547Dmo
    ports:
      - "5433:5432"  # O PostgreSQL dentro do container roda na 5432, mas no host podes acessar pela 5433
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d 

volumes:
  db_data:
